version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Named volume for the web service
    environment:
      DJANGO_SETTINGS_MODULE: app.settings
      PYTHONUNBUFFERED: 1
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  # Persistent volume for the database
  web_data:       # Persistent volume for the web service
