# Generated by Django 5.2 on 2025-04-19 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchproduct',
            old_name='product',
            new_name='model',
        ),
    ]
