# Generated by Django 5.1.5 on 2025-01-18 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_producthistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="warranty_period",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999),
                ],
            ),
        ),
    ]
